# Generated by Django 3.2.6 on 2021-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=100, verbose_name='Consultant Name')),
                ('uid', models.CharField(max_length=100, verbose_name='UID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('eda_vendor', models.CharField(max_length=100, verbose_name='EDA Vendor')),
                ('consultant_type', models.CharField(max_length=100, verbose_name='Consultant Type')),
                ('technology_focus', models.CharField(max_length=100, verbose_name='Technology Focus')),
                ('access_type', models.CharField(max_length=100, verbose_name='Access Type')),
                ('consultant_start_date', models.DateField(verbose_name='Consultant Start Date')),
                ('proposed_end_date', models.DateField(verbose_name='Proposed End Date')),
                ('qcm_consultant_current_status', models.CharField(max_length=100, verbose_name='QCM Consultant Current Status')),
                ('off_board_consultant', models.CharField(max_length=100, verbose_name='Off-Board Consultant (Y/N)')),
                ('current_vpn_status', models.CharField(max_length=100, verbose_name='VPN Current Status')),
                ('consultant_location', models.CharField(max_length=100, verbose_name='Consultant Location')),
                ('current_consultant_sponsor', models.CharField(max_length=100, verbose_name='Current Consultant Sponsor')),
                ('project', models.CharField(max_length=100, verbose_name='Project')),
                ('justificaiton_for_remaining_onboarded', models.TextField(max_length=1000, verbose_name='Justification for Consultant to Remain Onboarded (Specify Deliverables/Scope)')),
                ('approval_for_justification', models.CharField(max_length=100, verbose_name='GCAD Sr. Director Approval')),
                ('approval_comments', models.CharField(max_length=100, verbose_name='Comments')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
