# Generated by Django 3.2.6 on 2021-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210815_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='approval_comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='approval_for_justification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GCAD Sr. Director Approval'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='consultant_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consultant Location'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='justificaiton_for_remaining_onboarded',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Justification for Consultant to Remain Onboarded (Specify Deliverables/Scope)'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='off_board_consultant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Off-Board Consultant (Y/N)'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project'),
        ),
    ]
