# Generated by Django 3.2.8 on 2021-10-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210815_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ['id']},
        ),
    ]
