# Generated by Django 3.2.8 on 2021-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_consultant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='dummy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dummy'),
        ),
    ]
