# Generated by Django 3.2.8 on 2021-10-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_consultant_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='dummy',
        ),
    ]
