# Generated by Django 3.2.8 on 2021-10-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_custommodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodel',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
