# Generated by Django 3.2.8 on 2021-10-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_custommodel_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommodel',
            options={},
        ),
    ]
